// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps.js';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = [
      'path',
      'id',
      'parentId',
      'isLayout',
      'isWrapper',
      'layout',
      'clientLoader',
    ];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`,
        );
      }
    });
  });
}

import React from 'react';

export async function getRoutes() {
  const routes = {
    '404': { id: '404', path: '*', parentId: 'DocLayout' },
    'dumi-context-layout': { id: 'dumi-context-layout', path: '/', isLayout: true },
    DocLayout: { id: 'DocLayout', path: '/', parentId: 'dumi-context-layout', isLayout: true },
    'docs/guide': { path: 'guide', id: 'docs/guide', parentId: 'DocLayout' },
    'docs/index': { path: '', id: 'docs/index', parentId: 'DocLayout' },
    'components/Button/index': {
      id: 'components/Button/index',
      path: 'components/button',
      parentId: 'DocLayout',
    },
    'components/Card/index': {
      id: 'components/Card/index',
      path: 'components/card',
      parentId: 'DocLayout',
    },
    'demo-render': {
      id: 'demo-render',
      path: '~demos/:id',
      parentId: 'dumi-context-layout',
      prerender: false,
    },
  } as const;
  return {
    routes,
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.14_6qu4yv6hwoqszipfct7w7cgcri__node_modules__dumi__dist__client__pages__404" */ '/Users/zhanghaowen/Desktop/SXF-DESIGN/node_modules/.pnpm/dumi@2.1.14_6qu4yv6hwoqszipfct7w7cgcri/node_modules/dumi/dist/client/pages/404.js'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */ '/Users/zhanghaowen/Desktop/SXF-DESIGN/.dumi/tmp/dumi/theme/ContextWrapper.tsx'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.14_6qu4yv6hwoqszipfct7w7cgcri__node_modules__dumi__theme-default__layouts__DocLayout__index" */ '/Users/zhanghaowen/Desktop/SXF-DESIGN/node_modules/.pnpm/dumi@2.1.14_6qu4yv6hwoqszipfct7w7cgcri/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
          ),
      ),
      'docs/guide': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide.md" */ '/Users/zhanghaowen/Desktop/SXF-DESIGN/docs/guide.md'
          ),
      ),
      'docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ '/Users/zhanghaowen/Desktop/SXF-DESIGN/docs/index.md'
          ),
      ),
      'components/Button/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__sxf-design__src__components__Button__index.md" */ '/Users/zhanghaowen/Desktop/SXF-DESIGN/packages/sxf-design/src/components/Button/index.md'
          ),
      ),
      'components/Card/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "packages__sxf-design__src__components__Card__index.md" */ '/Users/zhanghaowen/Desktop/SXF-DESIGN/packages/sxf-design/src/components/Card/index.md'
          ),
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.14_6qu4yv6hwoqszipfct7w7cgcri__node_modules__dumi__dist__client__pages__Demo__index" */ '/Users/zhanghaowen/Desktop/SXF-DESIGN/node_modules/.pnpm/dumi@2.1.14_6qu4yv6hwoqszipfct7w7cgcri/node_modules/dumi/dist/client/pages/Demo/index.js'
          ),
      ),
    },
  };
}
