// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhanghaowen/Desktop/SXF/SXF-DESIGN/node_modules/.pnpm/dumi@2.1.14_33wpwrquqfbcdpvbd6l6oyhgce/node_modules/dumi/theme-default/slots/PreviewerActions/index.js';
