// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp';
export type { RuntimeConfig } from './core/defineApp';
// @umijs/renderer-*
export {
  createBrowserHistory,
  createHashHistory,
  createMemoryHistory,
  Helmet,
  createSearchParams,
  generatePath,
  matchPath,
  matchRoutes,
  Navigate,
  NavLink,
  Outlet,
  resolvePath,
  useLocation,
  useMatch,
  useNavigate,
  useOutlet,
  useOutletContext,
  useParams,
  useResolvedPath,
  useRoutes,
  useSearchParams,
  useAppData,
  useClientLoaderData,
  useRouteProps,
  useSelectedRoutes,
  useServerLoaderData,
  renderClient,
  __getRoot,
  Link,
  useRouteData,
  __useFetcher,
  withRouter,
} from '/Users/zhanghaowen/Desktop/SXF/SXF-DESIGN/node_modules/.pnpm/@umijs+renderer-react@4.0.53_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react';
export type { History } from '/Users/zhanghaowen/Desktop/SXF/SXF-DESIGN/node_modules/.pnpm/@umijs+renderer-react@4.0.53_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react';
// umi/client/client/plugin
export {
  ApplyPluginsType,
  PluginManager,
} from '/Users/zhanghaowen/Desktop/SXF/SXF-DESIGN/node_modules/.pnpm/umi@4.0.53_nhktnckc7qi62wkqw7ym4grfaa/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
// plugins types.d.ts
